name: Analyze Code

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze